language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kboudy/udemy-docker-kubernetes-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kboudy/udemy-docker-kubernetes-react npm run test
